services:
  postgres:
    image: postgres:15
    container_name: streamtoolkit-postgres
    environment:
      POSTGRES_DB: streamtoolkit
      POSTGRES_USER: ${DB_USERNAME:-myuser}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-mypassword}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U myuser -d streamtoolkit"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: 